name = "funnel-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[drawing]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "funnel-db"
database_id = "to-be-replaced-after-creation"

[[rules]]
type = "Text"
globs = ["**/client.js"]
fallthrough = false

[[kv_namespaces]]
binding = "LANDING_PAGE_CONTENT"
id = "preview" # User must replace this with real ID for production
preview_id = "preview"
